---

- hosts: all
  become: true
  tasks:
   - name: update repository index
     dnf:
      update_cache: yes
     when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "8"

   - name: install apache(httpd) package
     dnf:
      name: httpd
      state: latest
     when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "8"

   - name: ensure httpd is started
     systemd:
      name: httpd
      state: started
     when: ansible_distribution == "Rocky" and ansible_distribution_major_version == "8"

   - name: copy default html file for site
     tags: apache, httpd
     copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: spectrum
      group: wheel
      mode: 0644
       
