---
- name: Add HashiCorp Repo
  hosts: all
  become: yes #run as root

  tasks:
   - name: Add HashiCorp repository
     yum_repository:
      name: hashicorp
      description: HashiCorp Stable - $basearch
      baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable

